Repository fylein/fyle-netsuite-api, pull requests merged in 2024-12, with the labels that each got.

#685 fix: delete `expense_attributes_deletion_cache` in workspace reset
  scripts/sql/functions/reset-workspace.sql
Labels: size/XS

#686 chore: bump accounting mapping version
  requirements.txt
Labels: size/XS

#687 Feat: Add toggle for enabling uploading attachments
  apps/netsuite/tasks.py
  apps/workspaces/migrations/0041_configuration_is_attachment_upload_enabled.py
  apps/workspaces/models.py
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
  tests/test_workspaces/data.json
Labels: size/M

#688 Feat: Add created_at, created_at to workspace_schedule and workspaces…
  apps/users/models.py
  apps/workspaces/migrations/0042_auto_20241219_1808.py
  apps/workspaces/models.py
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
  tests/test_workspaces/data.json
Labels: size/M

#689 Feat: Adding Created_by and updated_by to conf tables
  apps/fyle/migrations/0037_auto_20241226_0929.py
  apps/fyle/models.py
  apps/fyle/views.py
  apps/mappings/migrations/0016_auto_20241226_0929.py
  apps/mappings/models.py
  apps/workspaces/apis/export_settings/serializers.py
  apps/workspaces/apis/export_settings/views.py
  apps/workspaces/apis/import_settings/serializers.py
  apps/workspaces/apis/import_settings/views.py
  apps/workspaces/apis/map_employees/serializers.py
  apps/workspaces/apis/map_employees/views.py
  apps/workspaces/migrations/0043_auto_20241224_1102.py
  apps/workspaces/models.py
  requirements.txt
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
  tests/test_fyle/fixtures.py
  tests/test_fyle/test_models.py
  tests/test_workspaces/data.json
  tests/test_workspaces/test_views.py
Labels: size/M

#690 Feat: Version bump for fyle-accounting-mapping fields
  requirements.txt
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
Labels: size/S
