Repository fylein/fyle-netsuite-api, pull requests merged in 2024-10, with the labels that each got.

#638 feat: Add generators in syncing dimensions
  apps/netsuite/connector.py
  tests/test_netsuite/fixtures.py
  tests/test_netsuite/test_connector.py
Labels: deploy, size/M

#646 fix: handle post acconting summary
  apps/netsuite/tasks.py
Labels: size/M

#648 fix: activity stats
  requirements.txt
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
  tests/test_netsuite/fixtures.py
Labels: size/XL

#649 feat: Added limits to attributes
  apps/netsuite/connector.py
  requirements.txt
  tests/test_mappings/test_tasks.py
  tests/test_netsuite/test_connector.py
Labels: size/L

#650 feat: Log worker Id for export async task
  apps/netsuite/tasks.py
  fyle_netsuite_api/logging_middleware.py
  fyle_netsuite_api/settings.py
Labels: size/M

#653 fix: expense group creation
  apps/fyle/tasks.py
  apps/workspaces/tasks.py
Labels: size/XS

#654 fix: default tax code
  apps/workspaces/apis/import_settings/serializers.py
Labels: size/XS

#651 feat: Add middleware to log all post requests.
  fyle_netsuite_api/logging_middleware.py
  fyle_netsuite_api/settings.py
Labels: size/S

#656 test: add tests for single credit line <> JE
  apps/netsuite/connector.py
  apps/workspaces/apis/advanced_settings/serializers.py
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
  tests/test_netsuite/fixtures.py
  tests/test_netsuite/test_connector.py
  tests/test_workspaces/data.json
  tests/test_workspaces/test_apis/test_advanced_settings/fixtures.py
Labels: size/M
