Repository fylein/fyle-netsuite-api, pull requests merged in 2024-09, with the labels that each got.

#637 Max retry for vendor payment limit
  apps/netsuite/migrations/0026_auto_20240902_1650.py
  apps/netsuite/models.py
  apps/netsuite/tasks.py
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
  tests/test_netsuite/test_tasks.py
Labels: deploy

#640 fix cc mapping creation
  apps/workspaces/apis/export_settings/triggers.py
Labels: deploy

#641 chore: Added github action
  .github/pull_request_template.md
  .github/workflows/pr_size.yml
Labels: size/S

#645 feat: Add Receipt URL
  apps/netsuite/migrations/0027_auto_20240924_0820.py
  apps/netsuite/models.py
  apps/netsuite/tasks.py
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
  tests/test_netsuite/test_tasks.py
Labels: deploy, size/M

#647 fix: PR Size CI Version Update
  .github/workflows/pr_size.yml
Labels: size/XS
