Repository fylein/fyle-netsuite-api, pull requests merged in 2024-11, with the labels that each got.

#659 fix: fix export url generation for sandbox accounts
  fyle_netsuite_api/utils.py
  scripts/sql/scripts/029-update-sandbox-export-urls.sql
Labels: deploy, size/S

#660 fix: add transaction block
  apps/netsuite/connector.py
Labels: size/XS

#663 fix: remove sentry transaction sampling
  fyle_netsuite_api/sentry.py
Labels: size/XS

#664 feat: update netsuite sdk/wsdl version
  requirements.txt
Labels: size/XS

#665 Fix: Remove code for adding department in expense group settings
  apps/workspaces/apis/import_settings/triggers.py
Labels: size/S

#666 fix: add unique constraint in task_logs for expense_group
  apps/tasks/migrations/0012_alter_tasklog_expense_group.py
  apps/tasks/models.py
Labels: size/S

#661 feat: handle posted at
  apps/fyle/migrations/0034_expense_is_posted_at_null.py
  apps/fyle/models.py
  apps/workspaces/migrations/0040_alter_configuration_change_accounting_period.py
  apps/workspaces/models.py
  requirements.txt
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
  tests/test_netsuite/conftest.py
Labels: size/M

#669 fix: get tax mapping
  apps/netsuite/models.py
Labels: size/XS

#662 feat: Netsuite Tax Override
  apps/mappings/migrations/0015_generalmapping_is_tax_balancing_enabled.py
  apps/mappings/models.py
  apps/netsuite/connector.py
  apps/netsuite/models.py
  apps/netsuite/tasks.py
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
  tests/test_netsuite/conftest.py
  tests/test_netsuite/fixtures.py
  tests/test_netsuite/test_connector.py
  tests/test_netsuite/test_tasks.py
Labels: deploy, size/XL

#677 feat: support multiple line items for CC charge exports
  apps/netsuite/connector.py
  apps/netsuite/models.py
  apps/netsuite/tasks.py
  tests/test_fyle/fixtures.py
  tests/test_netsuite/conftest.py
  tests/test_netsuite/test_connector.py
  tests/test_netsuite/test_models.py
Labels: size/L

#676 feat: add script for split expense grouping
  apps/netsuite/connector.py
  apps/netsuite/models.py
  apps/netsuite/tasks.py
  scripts/sql/scripts/030-default-split-expense-grouping-for-old-orgs.sql
  tests/test_fyle/fixtures.py
  tests/test_netsuite/conftest.py
  tests/test_netsuite/test_connector.py
  tests/test_netsuite/test_models.py
Labels: size/L

#675 feat: implement split expense grouping functionality
  apps/fyle/models.py
  apps/netsuite/connector.py
  apps/netsuite/models.py
  apps/netsuite/tasks.py
  scripts/sql/scripts/030-default-split-expense-grouping-for-old-orgs.sql
  tests/test_fyle/fixtures.py
  tests/test_netsuite/conftest.py
  tests/test_netsuite/test_connector.py
  tests/test_netsuite/test_models.py
Labels: size/L

#672 feat: support GET and PUT for `split_expense_grouping` in export settings
  apps/fyle/models.py
  apps/netsuite/connector.py
  apps/netsuite/models.py
  apps/netsuite/tasks.py
  apps/workspaces/apis/export_settings/serializers.py
  scripts/sql/scripts/030-default-split-expense-grouping-for-old-orgs.sql
  tests/test_fyle/fixtures.py
  tests/test_netsuite/conftest.py
  tests/test_netsuite/test_connector.py
  tests/test_netsuite/test_models.py
Labels: size/L

#681 feat: support split expense grouping
  apps/fyle/migrations/0035_support_split_expense_grouping.py
  apps/fyle/models.py
  apps/netsuite/connector.py
  apps/netsuite/models.py
  apps/netsuite/tasks.py
  apps/workspaces/apis/export_settings/serializers.py
  scripts/sql/scripts/030-default-split-expense-grouping-for-old-orgs.sql
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
  tests/test_fyle/conftest.py
  tests/test_fyle/fixtures.py
  tests/test_fyle/test_models.py
  tests/test_netsuite/conftest.py
  tests/test_netsuite/test_connector.py
  tests/test_netsuite/test_models.py
  tests/test_workspaces/test_apis/test_export_settings/fixtures.py
Labels: size/L

#682 fix: include receipt links in all line items for cc charges
  apps/netsuite/tasks.py
Labels: size/XS

#679 feat: Add internal API for get exported entry
  apps/internal/actions.py
  apps/internal/urls.py
  apps/internal/views.py
  apps/netsuite/connector.py
  tests/test_internal/test_actions.py
  tests/test_internal/test_views.py
Labels: size/M

#678 test: get accounting field internal API
  apps/internal/actions.py
  apps/internal/urls.py
  apps/internal/views.py
  apps/netsuite/connector.py
  tests/test_internal/test_actions.py
  tests/test_internal/test_views.py
Labels: size/M

#658 feat: NetSuite Internal APIs
  apps/internal/__init__.py
  apps/internal/actions.py
  apps/internal/apps.py
  apps/internal/migrations/__init__.py
  apps/internal/urls.py
  apps/internal/views.py
  apps/netsuite/connector.py
  apps/workspaces/permissions.py
  apps/workspaces/views.py
  fyle_netsuite_api/settings.py
  fyle_netsuite_api/urls.py
  tests/test_internal/test_actions.py
  tests/test_internal/test_views.py
Labels: size/L

#673 feat: add masked corporate card number and employee name
  apps/fyle/migrations/0036_expense_masked_corporate_card_number.py
  apps/fyle/models.py
  apps/netsuite/models.py
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
Labels: size/S

#683 fix: Update API path
  fyle_netsuite_api/urls.py
Labels: deploy, size/XS

#684 fix: tax validate
  apps/netsuite/tasks.py
Labels: size/XS
