Repository fylein/fyle-netsuite-api, pull requests merged in 2025-04, with the labels that each got.

#739 chore: Add Security Scan Workflow
  .github/workflows/security-scan.yml
Labels: size/S

#752 fix: update setuptools, wheel
  Dockerfile
Labels: size/XS

#745 Feat: Add Bill Refund
  apps/fyle/helpers.py
  apps/fyle/models.py
  tests/test_fyle/fixtures.py
  tests/test_fyle/test_models.py
Labels: size/XL

#753 chore: Add expense index & handle post accounting export summary
  apps/fyle/actions.py
  apps/fyle/migrations/0039_expense_expenses_account_ff34f0_idx_and_more.py
  apps/fyle/migrations/0040_alter_expense_imported_from.py
  apps/fyle/models.py
  apps/fyle/tasks.py
  apps/internal/tasks.py
  apps/netsuite/actions.py
  apps/netsuite/exceptions.py
  apps/netsuite/tasks.py
  apps/tasks/migrations/0014_alter_tasklog_triggered_by.py
  requirements.txt
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
  tests/test_fyle/test_tasks.py
Labels: size/M

#757 fix: post accounting export summary params
  apps/fyle/tasks.py
  apps/netsuite/actions.py
  apps/netsuite/exceptions.py
  apps/netsuite/tasks.py
Labels: size/XS

#759 feat: move to v1
  apps/mappings/tasks.py
  apps/users/views.py
  requirements.txt
  tests/conftest.py
  tests/test_fyle/test_actions.py
  tests/test_fyle/test_helpers.py
  tests/test_fyle/test_platform_connector.py
  tests/test_fyle/test_views.py
  tests/test_mappings/test_tasks.py
  tests/test_netsuite/test_tasks.py
  tests/test_users/test_helpers.py
  tests/test_workspaces/test_tasks.py
Labels: deploy, size/M

#760 chore: bump libraries
  requirements.txt
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
Labels: size/XS

#754 feat: Skip mapping error export
  apps/netsuite/exceptions.py
  apps/netsuite/queue.py
  apps/netsuite/tasks.py
  apps/tasks/migrations/0015_error_mapping_error_expense_group_ids.py
  apps/tasks/models.py
  apps/workspaces/apis/errors/serializers.py
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
  tests/test_fyle/test_views.py
  tests/test_netsuite/test_tasks.py
Labels: size/L

#761 chore: Skip accountin export summary post and more
  apps/fyle/actions.py
  apps/internal/tasks.py
  apps/workspaces/migrations/0045_configuration_skip_accounting_export_summary_post.py
  apps/workspaces/models.py
  apps/workspaces/serializers.py
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
Labels: size/S

#763 fix: last spent at configuration
  apps/fyle/models.py
  apps/netsuite/models.py
Labels: size/XS

#758 Feat: Expenses can be skipped after being imported to integration
  apps/fyle/actions.py
  apps/fyle/apps.py
  apps/fyle/models.py
  apps/fyle/signals.py
  apps/fyle/tasks.py
Labels: deploy, size/M
