Repository fylein/fyle-netsuite-api, pull requests merged in 2025-07, with the labels that each got.

#808 fix: ignore cursor rules
  .gitignore
Labels: size/XS

#809 fix: last export detail update for real-time users
  apps/workspaces/actions.py
Labels: size/XS

#762 feat: Netsuite health check api support
  .gitignore
  .gitleaksignore
  apps/internal/actions.py
  apps/mappings/exceptions.py
  apps/mappings/queue.py
  apps/mappings/signals.py
  apps/mappings/tasks.py
  apps/mappings/views.py
  apps/netsuite/exceptions.py
  apps/netsuite/helpers.py
  apps/netsuite/signals.py
  apps/netsuite/tasks.py
  apps/netsuite/views.py
  apps/workspaces/migrations/0048_netsuitecredentials_is_expired.py
  apps/workspaces/models.py
  apps/workspaces/tasks.py
  apps/workspaces/urls.py
  apps/workspaces/views.py
  fyle_netsuite_api/utils.py
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
  tests/test_netsuite/test_connector.py
  tests/test_netsuite/test_helpers.py
  tests/test_netsuite/test_tasks.py
  tests/test_netsuite/test_views.py
  tests/test_workspaces/test_models.py
  tests/test_workspaces/test_tasks.py
  tests/test_workspaces/test_views.py
Labels: size/L

#810 Feat: Fix skip export bug
  apps/fyle/tasks.py
Labels: size/XS

#811 fix: employee mapping creation
  apps/netsuite/tasks.py
  tests/test_netsuite/test_tasks.py
Labels: size/XS

#812 Feat: Fix throttling vulnerability
  fyle_netsuite_api/settings.py
Labels: size/XS

#819 Feat: Added lock for task_logs in export modules
  apps/netsuite/tasks.py
Labels: size/M

#822 feat: Vendor Creation Error Handling
  apps/netsuite/connector.py
Labels: size/XS

#823 chore: Upgrade accounting mapping version to 2.5.7
  requirements.txt
Labels: size/XS

#827 Fix: Fix bug in filter expense group function for expense report
  apps/fyle/models.py
Labels: size/XS

#831 chore: Update platform version 2.3.4
  apps/fyle/models.py
  requirements.txt
Labels: size/XS

#832 chore: Update fyle-integrations-platform-connector to 2.3.5
  requirements.txt
Labels: size/XS

#833 Fix: Fix referenced before assignment error
  apps/netsuite/connector.py
Labels: size/XS
