Repository fylein/fyle-netsuite-api, pull requests merged in 2025-05, with the labels that each got.

#764 fix: Expense group get for internal fun
  apps/internal/tasks.py
Labels: size/XS

#765 fix: add expense group condition
  apps/internal/tasks.py
Labels: size/XS

#766 fix: Reduce paginator size for accounting export summary post
  apps/fyle/actions.py
  apps/internal/tasks.py
Labels: size/XS

#768 Feat: Bump up integrations-platform-connector version
  requirements.txt
Labels: size/XS

#771 fix: Direct export -ve expense, token bug
  apps/fyle/models.py
  apps/fyle/tasks.py
  tests/test_fyle/fixtures.py
  tests/test_fyle/test_tasks.py
Labels: size/M

#772 chore: Add direct export loggers
  apps/fyle/actions.py
  fyle_netsuite_api/logging_middleware.py
Labels: size/S

#770 Feat: Only add _creditCard acctType to credit_card_account attibute_type
  apps/netsuite/connector.py
Labels: size/XS

#775 fix: update email redirect url from settings to admin app
  apps/workspaces/tasks.py
Labels: size/XS

#774 feat: Real-time exports, phase 2 - NetSuite
  apps/fyle/helpers.py
  apps/fyle/signals.py
  apps/fyle/tasks.py
  apps/fyle/views.py
  apps/internal/tasks.py
  apps/netsuite/queue.py
  apps/netsuite/views.py
  apps/workspaces/actions.py
  apps/workspaces/apis/advanced_settings/serializers.py
  apps/workspaces/apis/advanced_settings/triggers.py
  apps/workspaces/migrations/0046_workspaceschedule_is_real_time_export_enabled.py
  apps/workspaces/models.py
  apps/workspaces/tasks.py
  apps/workspaces/urls.py
  apps/workspaces/views.py
  requirements.txt
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
  tests/test_fyle/test_signals.py
  tests/test_fyle/test_tasks.py
  tests/test_workspaces/data.json
  tests/test_workspaces/test_apis/test_advanced_settings/fixtures.py
  tests/test_workspaces/test_tasks.py
  tests/test_workspaces/test_views.py
  workers/export/worker.py
Labels: size/L

#776 Fix: Resolve gst pst amount cannot be negative! error
  apps/netsuite/connector.py
Labels: deploy, size/XS

#783 fix: update workspace schedule for turning off real-time
  apps/workspaces/tasks.py
Labels: size/XS
