Repository fylein/fyle-netsuite-api, pull requests merged in 2025-03, with the labels that each got.

#712 feat: patch integrations-settings-api on export errors
  apps/fyle/helpers.py
  apps/netsuite/actions.py
  apps/workspaces/tasks.py
  tests/test_netsuite/fixtures.py
  tests/test_netsuite/test_actions.py
Labels: size/M

#728 feat: Restructure Direct Export
  apps/fyle/actions.py
  apps/fyle/helpers.py
  apps/fyle/queue.py
  apps/fyle/tasks.py
  apps/netsuite/exceptions.py
  apps/netsuite/queue.py
  apps/netsuite/tasks.py
  tests/test_fyle/test_queue.py
  tests/test_netsuite/test_models.py
  tests/test_netsuite/test_tasks.py
Labels: deploy, size/M

#730 fix: Django Vul
  requirements.txt
Labels: size/XS

#731 fix: TLS vulnerability
  Dockerfile
  docker-compose-pipeline.yml
  init.sql
  tests/conftest.py
  tests/sql_fixtures/reset_db_fixtures/reset_db.sh
Labels: size/S

#734 Feat: Added health check
  Dockerfile
  health_check.sh
Labels: size/S

#736 fix: Retry Stuck Tasks bug
  apps/internal/tasks.py
Labels: size/XS

#735 fix: Run container with non root user
  Dockerfile
  docker-compose-pipeline.yml
Labels: size/S

#741 fix: Revert "fix: Run container with non root user (#735)"
  Dockerfile
  docker-compose-pipeline.yml
Labels: size/S

#740 fix: mapping settings change
  apps/workspaces/apis/export_settings/serializers.py
  apps/workspaces/apis/export_settings/triggers.py
  apps/workspaces/apis/import_settings/triggers.py
  tests/test_workspaces/test_apis/test_export_settings/test_triggers.py
Labels: deploy, size/M

#738 Feat: Add updated_at in bulk updates and update
  apps/fyle/actions.py
  apps/fyle/models.py
  apps/fyle/tasks.py
  apps/mappings/signals.py
  apps/mappings/tasks.py
  apps/netsuite/connector.py
  apps/netsuite/tasks.py
  apps/workspaces/apis/import_settings/triggers.py
Labels: size/M
